import Fishers_Iris_Analysis_summary
Fishers_Iris_Analysis_summary.meanVirginica()
Fishers_Iris_Analysis_summary.meanVericolor()
Fishers_Iris_Analysis_summary.meanSetosa()
Fishers_Iris_Analysis_summary.stdDevVirginica()
Fishers_Iris_Analysis_summary.stdDevVericolor()
Fishers_Iris_Analysis_summary.stdDevSetosa()
Fishers_Iris_Analysis_summary.displayDDmatrix()